name: uniner-train
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pyyaml
  - pip:
      - accelerate
      - fastapi
      - gradio==3.23
      - httpx
      - markdown2[all]
      - nh3
      - prompt_toolkit>=3.0.0
      - pydantic
      - requests
      - rich>=10.0.0
      - sentencepiece
      - shortuuid
      - tokenizers>=0.12.1
      - transformers>=4.28.0,<4.29.0
      - uvicorn
      - wandb
